### ISSUE TITLE
MrPotatoMagic - OOG scenario can occur in multiple AutomationVault functions

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-xkeeper-judging#113]
MrPotatoMagic

medium

# OOG scenario can occur in multiple AutomationVault functions

## Summary

Most functions in the AutomationVault.sol contract use multiple for loops with nesting to perform add() and remove() operations on callers, jobs and selectors data of a relay.

## Vulnerability Detail

The functions that would be mainly affected are:
1. [deleteRelay()](https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L207)
2. [modifyRelayJobs()](https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L319)

The second function modifyRelayJobs() mentioned above is more gas intensive since it includes the use of 4 for loops i.e. 2 nested loops. The function modifies the data associated with a relay by first deleting the existing data (old jobs and selectors) and then adding the new data (new jobs and selectors). Both processes would use up more gas as the owner increases size of jobs and selectors causing higher number of iterations to occur.

## Impact

The issue is that if the number of callers, jobs or selectors for a particular relay increase in size, there is a high chance that deletions and modifications would revert, thus making the owner devoid of changing any data. 

## Code Snippet

How to use this POC:
 - Add the POC to AutomationVault.t.sol in the `test/unit` folder within the `UnitAutomationVaultModifyRelayJobs` contract located in the file.
 - Run the POC using `forge test --match-test testRelayJobsAndSelectorsAreModifiedIssue -vvvvv`
 - The gas used by the modifyRelayJobs() function call would be around 15 million (estimations vary quite a bit in foundry). If we bump up the numbers by a bit in the for loop of the POC, we'll encounter an OOG exception causing a revert. In general, the current gas used up is extremely high as well since it's way higher than the average gas limit.
```solidity
  function testRelayJobsAndSelectorsAreModifiedIssue(
    address _relay,
    address _job,
    bytes4[] memory _selectors
  ) public happyPath(_relay, _job, _selectors) {
    // Get the list of jobs data for the relay
    (, IAutomationVault.JobData[] memory _jobsData) = automationVault.getRelayDataForTest(_relay);

    // Length should be zero
    assertEq(_jobsData.length, 0);

    //_jobsData = _createJobsData(_job, _selectors);

    _jobsData = new IAutomationVault.JobData[](100);
    for (uint256 i; i < 100 ; i++) {
      _jobsData[i].job = _job;
      _jobsData[i].functionSelectors = _selectors;
    }

    // Modify the relay jobs
    automationVault.modifyRelayJobs(_relay, _jobsData);

    // Get the list of jobs data for the relay
    (, _jobsData) = automationVault.getRelayDataForTest(_relay);

    for (uint256 _i; _i < _jobsData.length; ++_i) {
      assertEq(_jobsData[_i].job, _job);
      assertEq(_jobsData[_i].functionSelectors.length, _cleanSelectors.length());

      for (uint256 _j; _j < _jobsData[_i].functionSelectors.length; ++_j) {
        assertEq(_jobsData[_i].functionSelectors[_j], _cleanSelectors.at(_j));
      }
    }
  }
```

## Tool used

Manual Review

## Recommendation

Allow the owner to delete old jobs and selectors in a separate function and introduce a new function to allow owner to update new jobs and selectors for the relay. This is the most simplistic solution I could think of though there are many ways to go about this e.g. introducing start and end indexes to allow owner to perform operations in batches.

**Comment by mcgrathcoutinho** [comment]
Escalate
Hi @Hash01011122, I believe there is a misunderstanding. The issue is not talking about how an attacker causes this scenario but how the current implementation is gas intensive and could lead to frequent OOG exceptions. I'm not sure if Kose is the sponsor but I agree with Medium-severity here due to OOG being classified as a Med in docs.

**Comment by sherlock-admin2** [comment]
> Escalate
> Hi @Hash01011122, I believe there is a misunderstanding. The issue is not talking about how an attacker causes this scenario but how the current implementation is gas intensive and could lead to frequent OOG exceptions. I'm not sure if Kose is the sponsor but I agree with Medium-severity here due to OOG being classified as a Med in docs.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by kosedogus** [comment]
Escalate

I believe the comment from @Hash01011122 above is for another issue (possibly #60 ?) and this one is not related to that finding or findings related to additional bytes in calldata. So, I would like this to be reconsidered with its duplicates: #141, #144, #166. Thank you.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe the comment from @Hash01011122 above is for another issue (possibly #60 ?) and this one is not related to that finding or findings related to additional bytes in calldata. So, I would like this to be reconsidered with its duplicates: #141, #144, #166. Thank you.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by kosedogus** [comment]
Saw [this](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/144#issuecomment-2073651248) comment, and can say the followings regarding to it:
In the POC submitted with #144, indeed there is 5000 callers but the `values` function is not just used with *callers EnumerableSet*. It is also used with *job's EnumerableSet* and *jobSelectors' EnumerableSet*. Hence even if "expecting 5000 callers is impractical" according to sponsors comment, OOG can still occur with somewhat practical caller amount, job amount and jobSelector amount. If you run the following POC that I will provide below, you will see that modify calls require more than 10 million gas when there are:
1 relay, ≈15 caller, 2 job, ≈150 selector. It is possible for automationVault to be used with multiple relays which can potentially double or triple this amount, it is possible for it to have more than 2 job contracts obviously which again will effect gas amount immensely, when there are more than 1 relay it is possible to expect more callers even if it is not still 5000, which will also effects gas amount.

POC:
```solidity
  function test_ModifyRelayGas(
    address _relay,
    address[] memory _callers,
    address _job,
    bytes4[] memory _selectors,
    address _secondJob,
    bytes4[] memory _secondSelectors
  ) public {
    _assumeRelayData(_relay, _callers, _job, _selectors);
    vm.assume(_job != address(0));
    vm.assume(_secondJob != address(0));
    vm.assume(_job != _secondJob);

    IAutomationVault.JobData[] memory _jobsData = new IAutomationVault.JobData[](2);
    _jobsData[0].job = _job;
    _jobsData[0].functionSelectors = _selectors;
    _jobsData[1].job = _secondJob;
    _jobsData[1].functionSelectors = _secondSelectors;

    vm.prank(owner);
    uint256 gasBefore = gasleft();
    automationVault.modifyRelay(_relay, _callers, _jobsData);
    uint256 gasAfter = gasleft();
    assertGt(10_000_000, gasBefore-gasAfter);
    (, IAutomationVault.JobData[] memory _relayJobsData) = automationVault.getRelayDataForTest(_relay);

    assertEq(_relayJobsData.length, 2);
  }
```
(It is actually a test written by xKeeper, just added gas check to it, to show it can easily reach more than 10 million gas.)

So excluding this finding because of impracticality of massive caller amount is not enough I believe since the gas is not just related to caller amount, it is also related to relay amounts, job contract amounts and jobSelectors amount.

**Comment by kosedogus** [comment]
Saw [this](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/144#issuecomment-2073651248) comment, and can say the followings regarding to it:
In the POC submitted with #144, indeed there is 5000 callers but the `values` function is not just used with *callers EnumerableSet*. It is also used with *job's EnumerableSet* and *jobSelectors' EnumerableSet*. Hence even if "expecting 5000 callers is impractical" according to sponsors comment, OOG can still occur with somewhat practical caller amount, job amount and jobSelector amount. If you run the following POC that I will provide below, you will see that modify calls require more than 10 million gas when there are:
1 relay, ≈15 caller, 2 job, ≈150 selector.  It is possible for automationVault to have more than 2 job contracts obviously which will effect gas amount immensely, it is still possible to expect more callers even if it is not still 5000, which will also effects gas amount.

POC:
```solidity
  function test_ModifyRelayGas(
    address _relay,
    address[] memory _callers,
    address _job,
    bytes4[] memory _selectors,
    address _secondJob,
    bytes4[] memory _secondSelectors
  ) public {
    _assumeRelayData(_relay, _callers, _job, _selectors);
    vm.assume(_job != address(0));
    vm.assume(_secondJob != address(0));
    vm.assume(_job != _secondJob);

    IAutomationVault.JobData[] memory _jobsData = new IAutomationVault.JobData[](2);
    _jobsData[0].job = _job;
    _jobsData[0].functionSelectors = _selectors;
    _jobsData[1].job = _secondJob;
    _jobsData[1].functionSelectors = _secondSelectors;

    vm.prank(owner);
    uint256 gasBefore = gasleft();
    automationVault.modifyRelay(_relay, _callers, _jobsData);
    uint256 gasAfter = gasleft();
    assertGt(10_000_000, gasBefore-gasAfter);
    (, IAutomationVault.JobData[] memory _relayJobsData) = automationVault.getRelayDataForTest(_relay);

    assertEq(_relayJobsData.length, 2);
  }
```
(It is actually a test written by xKeeper, just added gas check to it, to show it can easily reach more than 10 million gas.)

So excluding this finding because of impracticality of massive caller amount is not enough I believe since the gas is not just related to caller amount, it is also related to job contract amounts, and jobSelectors amount.

Of course it is still not something that every vault will encounter, and it's occurence will be rare. But it's practicality is not impossible and it seems like there are possible but rare ways to reach OOG.

**Comment by RealLTDingZhen** [comment]
Why would a user add a relay with 5000 selectors? I don't think it has any effect in practical use. The cost of adding such a relay is also too much.

**Comment by mcgrathcoutinho** [comment]
Hey @RealLTDingZhen,

Please read my POC, Kose's POC and comments by Kose, it does not require 5000 selectors.

**Comment by Vancelott** [comment]
Just to provide further clarification, my POC (#144) demonstrates how gas inefficient it would be to call values on the `approvedCallers` as it would cause OOG if the callers are 5000 or more. However, the value can be much less, and `modifyRelayCallers` will revert due to it being out of gas once all of the other loops and function calls are completed.

**Comment by ghost** [comment]
I maintain the position outlined in my previous comments, aligning with the reasoning presented by @kosedogus. From my perspective, this is a low/info severity issue. Additionally, there will be no out-of-gas (OOG) reverts, as the sponsors have conducted thorough calculations and confirmed this.

**Comment by cvetanovv** [comment]
This issue for me is `Low` and the main reason is that `Owner` is trusted and under normal circumstances, the OOG would not appear. 

The admin can control some of the parameters and the POC data are highly inflated and with a more realistic scenario, I don't think the OOG would occur.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kosedogus](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/113/#issuecomment-2075059392): rejected
