### ISSUE TITLE
Tricko - Keepers can execute the `fallback` method even if it's not one of the approved selectors for that job.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-xkeeper-judging#68]
Tricko

medium

# Keepers can execute the `fallback` method even if it's not one of the approved selectors for that job.

## Summary
Because `_dataToExecute.jobData` is explicitly converted to `bytes4` in `AutomationVault.exec()`, the keeper can call the fallback method of the job contract even if it's not an approved job selector. This allows the keeper to repeatedly invoke the fallback method to farm rewards from that job.

## Vulnerability Detail
Each job configured in the `AutomationVault` contract can have one or more approved selectors that the keeper can call. Below is a snippet from the `AutomationVault.exec()` function where the selectors are validated. First, it converts `_dataToExecute.jobData` to `bytes4` and checks if it matches one of the allowed selectors. If it does, the function proceeds to call that job contract with `_dataToExecute.jobData` as calldata.

```solidity
      // Check that the selector is approved to be called
      if (!_approvedJobSelectors[msg.sender][_dataToExecute.job].contains(bytes4(_dataToExecute.jobData))) {
        revert AutomationVault_NotApprovedJobSelector();
      }
      (_success,) = _dataToExecute.job.call(_dataToExecute.jobData);
      if (!_success) revert AutomationVault_ExecFailed();
```

However, the code assumes that `bytes4(_dataToExecute.jobData)` and `_dataToExecute.jobData` are equal, which is not always the case. If `_dataToExecute.jobData` is smaller than 4 bytes, the explicit conversion to `bytes4` will pad it with zero bytes, making `bytes4(_dataToExecute.jobData)` not equal to `_dataToExecute.jobData`.

Consider this example: for a specified job, the approved selector is `0x8df82800` (for the `settle(uint256)` function). If the keeper sends the malformed `0x8df828` as `_dataToExecute.jobData`, the selector validation will succeed, but when the job contract is called, no function selector will match `0x8df828`, causing the fallback method (if it exists) to be executed. Thus, the fallback method can be called even though it was never approved for that job.

This issue can be exploited under two conditions:
- One of the approved function selectors for that job must have one or more`0x00` trailing bytes.
- There must be a fallback method on the job contract.

Considering the uniform distribution of function selectors (a fair assumption given they are the output of keccak256), the first condition will be met in approximately 0.39% of all approved selectors (1 trailing `0x00` byte (1/256) + 2 trailing `0x00` bytes (1/65536) + ... ). Although the probabilities are low, as the `AutomationVault` is supposed to be a general keeper aggregator, these situations will arise and potentially be exploited.

By exploiting this issue, a malicious keeper can call `AutomationVault.exec()` without actually executing the intended job and instead only calling the `fallback` method, yet still receiving rewards. This can be done repeatedly to farm rewards from that job. If the fallback method also has negative side effects on the job, they can also be exploited by the malicious keeper.

See the POC below. To run the POC apply the diff patch below and run the following `test_POC` test.

```diff
diff --git a/xkeeper-core/solidity/test/integration/OpenRelay.t.sol b/xkeeper-core/solidity/test/integration/OpenRelay
.t.sol--
index 7b40c3b..fac6c2b 100644
--- a/xkeeper-core/solidity/test/integration/OpenRelay.t.sol
+++ b/xkeeper-core/solidity/test/integration/OpenRelay.t.sol
@@ -5,7 +5,25 @@ import {CommonIntegrationTest} from '../integration/Common.t.sol';
 
 import {IAutomationVault} from '../../interfaces/core/IAutomationVault.sol';
 
+contract Job {
+  event Settled();
+  event Fallback();
+
+  function settle(uint256) external {
+    // Do stuff
+    emit Settled();
+  }re--
+
+  fallback() external payable {
+    emit Fallback();
+  }re--
+}More--
+
+
 contract IntegrationOpenRelay is CommonIntegrationTest {
+
+  event Fallback();
+
   function setUp() public override {
     // AutomationVault setup
     CommonIntegrationTest.setUp();
@@ -32,6 +50,38 @@ contract IntegrationOpenRelay is CommonIntegrationTest {
     changePrank(bot);
   }
 
+  function test_POC() public {
+    // Start of setup
+    Job jobContract = new Job();
+
+    address[] memory _bots = new address[](1);
+    _bots[0] = bot;
+
+    bytes4[] memory _jobSelectors = new bytes4[](1);
+    // 0x8df82800 -> bytes4(keccak256(abi.encode("settle(uint256)")))
+    _jobSelectors[0] = bytes4(0x8df82800);
+
+    IAutomationVault.JobData[] memory _jobsData = new IAutomationVault.JobData[](1);
+    _jobsData[0] = IAutomationVault.JobData(address(jobContract), _jobSelectors);
+
+    changePrank(owner);
+    automationVault.modifyRelay(address(openRelay), _bots, _jobsData);
+    address(automationVault).call{value: 100 ether}('');
+
+    changePrank(bot);
+    // End of setup
+
+    IAutomationVault.ExecData[] memory _execData = new IAutomationVault.ExecData[](1);
+    // Malformed selector to trigger the execution of the fallback method;
+    bytes3 selector = bytes3(0x8df828);
+    _execData[0] = IAutomationVault.ExecData(address(jobContract), abi.encodePacked(selector));
+
+    // Check that the fallback method was executed instead of the settle(uint256) function.
+    vm.expectEmit(address(jobContract));
+    emit Fallback();
+    openRelay.exec(automationVault, _execData, bot);
+  }re--
+
```

## Impact
For jobs that match both conditions described above, the keeper can execute the `fallback` method despite it not being listed in the allowed selectors. This enables the keeper to farm rewards from that job or potentially trigger unintended side-effects from the `fallback` function.

## Code Snippet
https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L413-L418

## Tool used
Manual Review

## Recommendation
Consider checking that if `_dataToExecute.jobData` is at least 4 bytes long, thus preventing the issue described above from occurring.

**Comment by realfugazzi** [comment]
This should on the low severity range as it requires: 

- the vault owner to whitelist a 0 padded selector (super low prob)
- the contract to have a fallback function
- even if it has a fallback function, bypass any other security measure provided in that implementation and also speculate this could have a negative impact

**Comment by adam-idarrha** [comment]
I believe this issue should be classified as low severity, primarily due to its negligible impact on the protocol's overall functionality. The probability of encountering a function selector that ends with a trailing 0x00 is inherently low, approximately 0.39% under the assumption of a uniform distribution. This figure alone underscores the rarity of such occurrences.

Moreover, the fallback function in Solidity contracts typically does not contain mechanisms critical to the core security or functionality of the protocol, further diminishing the potential impact of this issue. To illustrate the rarity and thus, the minimal risk posed by this scenario, one can refer to the [ethereum signature database](https://www.4byte.directory/), which tracks function selectors. A cursory review of this resource will show that selectors ending in 0x00 are exceptionally uncommon.

According to the severity criteria outlined by Sherlock, for an issue to merit a medium severity rating, it should either result in a loss of funds or significantly break core functionality. This issue does neither:

1. Loss of Funds: There is no risk of fund loss associated with this issue.
2. Breaks Core Functionality: The issue does not affect the core operations or security mechanisms of the protocol.

Given these factors — low impact, extremely low likelihood, and no interference with critical protocol operations — this issue warrants a classification of low severity.

**Comment by adam-idarrha** [comment]
also #77 is a duplicate i don't know why it got excluded

**Comment by adamidarrha** [comment]
@Hash01011122 I believe this issue should be classified as low severity, primarily due to its negligible impact on the protocol's overall functionality. The probability of encountering a function selector that ends with a trailing 0x00 is inherently low, approximately 0.39% under the assumption of a uniform distribution. This figure alone underscores the rarity of such occurrences.

Moreover, the fallback function in Solidity contracts typically does not contain mechanisms critical to the core security or functionality of the protocol, further diminishing the potential impact of this issue. To illustrate the rarity and thus, the minimal risk posed by this scenario, one can refer to the [ethereum signature database](https://www.4byte.directory/), which tracks function selectors. A cursory review of this resource will show that selectors ending in 0x00 are exceptionally uncommon.

According to the severity criteria outlined by Sherlock, for an issue to merit a medium severity rating, it should either result in a loss of funds or significantly break core functionality. This issue does neither:

1. Loss of Funds: There is no risk of fund loss associated with this issue.
2. Breaks Core Functionality: The issue does not affect the core operations or security mechanisms of the protocol.

Given these factors — low impact, extremely low likelihood, and no interference with critical protocol operations — this issue warrants a classification of low severity.

**Comment by adamidarrha** [comment]
also #77 is a duplicate

**Comment by 0xMR0** [comment]
Escalate

This should be low severity issue.

Please check above @realfugazzi and @adamidarrha comments.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be low severity issue.
> 
> Please check above @realfugazzi and @adamidarrha comments.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by RealLTDingZhen** [comment]
Agree this is a low path

**Comment by retsoko** [comment]
Regarding the concerns raised by @adamidarrha:

1. Loss of Funds: If the job is configured to use OpenRelay, a malicious keeper could repeatedly exploit this to drain the vault due to the bonus 20% from gas fees.
2. Breaks Core Functionality: The primary function of the AutomationVault contract is to ensure that only approved selectors can be executed. Therefore, executing selectors not in the accepted list constitutes a breach of the protocol's security mechanism.

This issue differs from others that inflate gas costs by sending excessive calldata. In those cases, the correct selector is being called, thus executing the right function in the target contract. As argued in another issue (https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/60#issuecomment-2073693635), in such situations, the job admin might implement checks to prevent exploitation, such as requiring delays between successive calls or reverting if calldata is too large, thus reducing the extent of the exploit. However, in this case, a function outside the approved list is being called, so no safeguard checks are expected, allowing the malicious keeper to drain the vault through the gas fees bonus.

As pointed out by @realfugazzi, the main point of contention of this report is whether the low likelihood of the conditions (trailing zeros selector + fallback available) makes this a low severity issue. I acknowledge the probability is low, but it is far from being negligible, and with general adoption of the xKeeper protocol, instances where the two conditions match will arise. However, what can be considered negligible is totally subjective, so we will have to wait and see the judge and head of judging opinion on this matter.

**Comment by adamidarrha** [comment]
@retsoko 
1. "Loss Of Funds": any keeper added by the owner in openRelay is the owner's problem, if he is malicious the owner can always remove him. it's not xkeeper's job to check if keepers are malicious or not. plus your issue didn't talk about this.
2. you do bypass that restriction by being able to only call the fallback , i don't think it's any problem in any contract being able to call the fallback function , so the issue has no impact and like i said low likelihood.

it's not only the issue is low likelihood because of a function selector that needs to have trailing zero, also the function needs to have implemented a fallback function or the call will revert.
and as i said no impact on being able to call fallback function. but it's an interesting finding .

**Comment by ashitakah** [comment]
While it is true that the protocol will only add the jobs that it is interested in working and it can always remove them in case of vulnerability and very specific circumstances must be met, it is true that it may incur a loss of funds and it is a very interesting issue.

So I would give it low because of the rarity and also the jobs should not have fallback and are the responsibility of the protocol.

**Comment by ghost** [comment]
Agreeing with the @realfugazzi and @adamidarrha that there is no high impact such as immense loss of funds of protocol. 20% gas inflation doesn't constitute to high loss of funds, so using it as your main point of argument is flawed. If Watson can show exact mathematical model in which `xKeeper` will be experiencing high loss of funds or core functionality of protocol is getting affected with High impact, then I would consider it as medium.
@retsoko Do you want to add anything here?

**Comment by retsoko** [comment]
While limited to 20% in a single call, this vulnerability can be exploited multiple times within a single transaction, enabling the keeper to drain all ETH deposited in the AutomationVault without contributing any meaningful work to that vault.

But besides that, nothing to add.

**Comment by ghost** [comment]
Hey, I stand by what I mentioned earlier this can be considered low severity issue, leaving it to head of judge I will respect any decision he will be making in this regard.

**Comment by cvetanovv** [comment]
I agree with most of the comments and by Sherlock standards this issue is Low. 

Impact and likelihood are Low. Furthermore, the owner is trusted to add a keeper and can remove him if the keeper becomes malicious.

I am planning to accept the escalation and invalidate the issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xMR0](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/68/#issuecomment-2077490739): accepted

**Comment by Hash01011122** [comment]
@Evert0x @cvetanovv, Escalation here is should be rejected in accordance of sherlocks documentation.
> #### Rules for Escalation:
>Escalation will not be accepted in case the reward distribution is not affected.
