### ISSUE TITLE
s1ce - Owner can frontrun keeper by withdrawing funds before keeper is paid

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-xkeeper-judging#80]
s1ce

high

# Owner can frontrun keeper by withdrawing funds before keeper is paid

## Summary

Malicious AutonomousVault owner can wait for a keeper to send a transaction, frontrun and withdraw all funds from the AutonomousVault, and force the keeper transaction to revert and the keeper to pay a hefty sum in gas fees

## Vulnerability Detail

1. Malicious AutonomousVault owner waits for keeper to send transaction
2. Owner calls withdrawFunds, taking all the funds out of the AutonomousVault
3. Keeper transcation lands and reverts at the end because keeper cannot be paid
4. Keeper potentially loses a lot of money in gas fees

## Impact

Keeper loses out on reward and pays large gas fees

## Code Snippet

https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L125

## Tool used

Manual Review

## Recommendation

Prevent owner from instantaneously being able to withdraw funds

**Comment by s1ce** [comment]
Escalate

This seems like a valid issue and a way to cause loss of funds for the keeper

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This seems like a valid issue and a way to cause loss of funds for the keeper

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Would you mind to elaborate on why do you think it is valid @s1ce??

**Comment by cvetanovv** [comment]
This is from the Readme:
> Each automation vault has an owner, and that role is TRUSTED

The owner is trusted, and therefore the issue is invalid.

Planning to reject the escalation and leave the issue as is.

**Comment by s1ce** [comment]
@cvetanovv Here is the full excerpt from the README:

`From the README: Each automation vault has an owner, that role is TRUSTED for the vault itself, but RESTRICTED for the whole protocol.`

The owner is trusted with regards to handling their own automation vault, but should not be trusted in external affairs. In this case, the owner can cause a definite loss of funds for the keeper -- the keeper is not part of the vault itself, so I believe that this should be in scope.

**Comment by ghost** [comment]
I agree with @cvetanovv, even LSW and sponsors had the same take regarding this issue.
For this:
>The owner is trusted with regards to handling their own automation vault, but should not be trusted in external affairs.

Owner of the vault have access to functions which deals to its own Vault itself, frontrunning txn won't make any sense.

Do you want to add anything @s1ce ??

**Comment by s1ce** [comment]
@Hash01011122 My interpretation of that sentence is that owners are trusted not to grief the money in their own vaults. But if they can grief others, in this case by frontrunning and withdrawing money from the vault before keeper is paid, it should be in scope.

**Comment by RealLTDingZhen** [comment]
It is self-harm and is not a smart contract vulnerability. The owner does not pay the fee and the keeper does not do the job properly. I don't see an issue here.

**Comment by s1ce** [comment]
"The owner does not pay the fee and the keeper does not do the job properly"

Keeper loses out on almost the entire gas cost and doesn't get paid. It's not self harm; it's griefing the keeper. 

The correct way to address this is to put a delay period before the owner can withdraw.

**Comment by RealLTDingZhen** [comment]
I've submitted a similar issue in a past contest.

And I believe the [reason ](https://github.com/sherlock-audit/2024-02-rubicon-finance-judging/issues/53#issuecomment-1953037330)there can also invalidate this issue

**Comment by cvetanovv** [comment]
The most important point that invalidates this issue is that the owner is TRUSTED. Your issue even starts with "Malicious AutonomousVault owner".

You can see this comment from the protocol: https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/172#issuecomment-2090449220

I stand by my earlier decision and will reject the escalation.

**Comment by cvetanovv** [comment]
Due to much confusion around the written "Restricted Owner" rule on the Readme, we decided to put all issues related to owner restriction under one issue.   The reasons are several: 

- When they wrote about the owner restriction on the Readme, they didn't mean that the Owner should be restricted for the whole protocol. You can see the protocol's view on this [here](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/172#issuecomment-2090449220).
- Кeepers are essential actors in the protocol, and there is confusion about whether to count them as part of the protocol itself.
- In the beginning, the Head of Judge for this contest was the Czar. LSW @IllIllI000 had communicated with him, and he also, like me, thought the Owner was trusted and should not hurt the protocol in any way. Because of this, LSW was not looking for such issues.

I think a compromise solution for everyone is to put all "Restricted Owner" issues under one issue. 

Because of this, I will accept the escalation and make this problem Medium and duplicate it with [177](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/177), [183](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/183), [176](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/176), [173](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/173).

**Comment by ghost** [comment]
Agree with what @cvetanovv has mentioned here. This issue can be invalidated.

**Comment by cvetanovv** [comment]
An addition to my decision to reject the escalation is that even if the owner is restricted, according to the rules of Sherlock, it is Low Severity: "Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block."

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/80/#issuecomment-2076564121): rejected
