### ISSUE TITLE
s1ce - `isKeeper` can be called by job contracts, leading to lower payout for keeper

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-xkeeper-judging#84]
s1ce

high

# `isKeeper` can be called by job contracts, leading to lower payout for keeper

## Summary

`isKeeper` is called initially on the `KEEP3R_V2` contract in `Keep3rRelay` to set the initial gas. In fact, it is called twice. However, the job contracts that likely belong to the owner can call this function again during their execution, setting a new value of initial gas and leading to a lower payout for the keeper. 

## Vulnerability Detail

The code explicitly tries to prevent any of the job contracts from being `KEEP3R_V2`, so that the job contracts can't change the value of initialGas. However, the job contracts can still change this value as a message value during their execution (they just need to call `isKeeper` on the `KEEP3R_V2` contract). 

This leads to the payout for the keeper being much lower when `worked` is called, because the `initialGas` will be a much lower amount (in fact, malicious owner with malicious job contracts can keep it close to zero if they set the `initialGas` by calling `isKeeper` right before `worked` is called). 

## Impact

Keep3r Relay keeper will be paid much less than they should be

## Code Snippet

https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/Keep3rRelay.sol#L43

## Tool used

Manual Review

## Recommendation

Revert if the initial gas value has changed from what it was set to after the second call

**Comment by s1ce** [comment]
@Hash01011122 can you explain why this is excluded?

**Comment by s1ce** [comment]
Escalate

This seems valid, not sure why it was excluded.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This seems valid, not sure why it was excluded. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
@s1ce Why do you think this is valid?
When I saw this issue it didn't make sense to me as I didn't see any impact on how change in initial gas will get affect protocol in any manner.
It would be great if you could provide me detailed explanation on what you are trying to point out.

**Comment by cvetanovv** [comment]
I completely agree with the Lead Judge. I would advise you to write better issues because they are hard to understand.

I don't see why the Owner who is **TRUSTED** would call the function again to harm the Keeper. And even if for some reason the things you say happen, the impact is maximum `Low/Information`.

Planning to reject the escalation and leave the issue as is.

**Comment by s1ce** [comment]
@Hash01011122 The change in initial gas would mean that the payout calculation for the keeper would be lower (because they are paid based on the amount of gas used). The fact that the job contracts can arbitrarily change the value of initial gas is a definite issue.  

@cvetanovv I think you are misinterpreting the relevant part of the README. The owners of each individual vault are just random users who are enlisting keepers to perform jobs for them - no way they are trusted to not harm keepers. 

From the README: `Each automation vault has an owner, that role is TRUSTED for the vault itself, but RESTRICTED for the whole protocol.`

This clearly implies that vault owners are trusted with respect to their own vault (so they're able to withdraw their own funds), but if they can harm the rest of the protocol in any way, then this is a legitimate concern. In this case, they are harming keepers, which are part of the rest of the protocol and not the owner's individual vault. 

There's also no way this is Low/Information - this causes a definitely loss of funds for keepers.

**Comment by ghost** [comment]
I standby what I mentioned earlier, this is informational severity issue.

**Comment by s1ce** [comment]
Why is it informational when it causes a loss of funds?

**Comment by ghost** [comment]
Even if we consider L2 chains of EVM, the loss will be in the range 10 to 20% gas which is low severity, Another thing is Owner is trusted, argument of automation vault owner cannot be used to suffice it medium severity as access given to them is pretty much restricted by protocol.

**Comment by cvetanovv** [comment]
After consulting internally with the Sherlock team about what was written in the Readme about the Owner restriction, we decided that if the Owner can hurt the protоcol, then the issue will be valid.

This is written in the Readme:

Each automation vault has an owner, that role is TRUSTED for the vault itself but RESTRICTED for the whole protocol.

In the beginning, I supported the protocol's https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/172#issuecomment-2090449220 that by RESTRICTED they meant that they would not act maliciously and that they will act properly for each of their functions, but the truth is that they wrote otherwise. Readme has the most weight in decision making, so I will review all the issues again and if the OWNER can harm the protocol then the problem will be valid. I apologize for the inconvenience.

I agree with that issue the Owner can hurt the keepers so I plan to make it a Medium.

**Comment by Al-Qa-qa** [comment]
Dup https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/124

**Comment by IllIllI000** [comment]
@Evert0x  these changes are completely different from how Czarek would have judged the findings, and he was the judge when the contest was ongoing. It's extremly unfair to be told to interpret things one way, and then for it to change afterwards. This is the conversations I had with him https://gist.github.com/IllIllI000/2f0c7106632a5dd3b6fcd9b48713bf83 and there he said `If the admin is able not to set the trap, then it's low/info`. it's now being said that the admin can be an attacker. why am I being penalized for listening to the judge, and asking for clarification of the readme ahead of time, as you suggested I do? I even submitted it as low, because that was the suggestion, and then did no look further into any other admin attacks, since that was the directive

**Comment by kosedogus** [comment]
> I agree with that issue the Owner can hurt the keepers so I plan to make it a Medium.

@cvetanovv @ashitakah  Isn't keepers are responsible to check what they will execute, simulate the transaction before executing so that they will only execute jobs if they think it is valuable for them?  I don't understand how a keeper can be thought as a part of the protocol. README says vault owner's are RESTRICTED for the rest of the protocol, I believe the rest of the protocol in here is "other automation vault owners", not keepers. In this issue's case Keep3r itself has a protection for this kind of problems: If job is malicious, it will be slashed and disputed by Keep3r Network, and it will only effect the malicious job owner, so it won't have any effect on the rest of the protocol.

**Comment by ghost** [comment]
Agree with what @kosedogus has mentioned here. This issue can be invalidated.

**Comment by cvetanovv** [comment]
I agree with what @kosedogus said that keepers can do their own checking on whether to accept a job. Regardless of whether the owner is restricted, that issue remains Low severity.

Planning to reject the escalation and leave the issue as is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/84/#issuecomment-2076561864): rejected
